[build]
  publish = "_site"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
  
	cache-control = '''
	max-age=86.400,
	must-revalidate'''